language: java
jdk:
  - openjdk11

script:
  - cd /java/com/google/gson
  - mvn -f gson ProjectTest261P

install: mvn -f gson install -DskipTests=true

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2